# Generated by Django 4.2 on 2023-04-15 21:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='data',
            field=jsonfield.fields.JSONField(),
        ),
    ]
