# Generated by Django 3.0.14 on 2023-01-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_auto_20230114_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField()),
                ('title', models.CharField(max_length=30, verbose_name='Name od job offer')),
                ('company', models.CharField(max_length=15, verbose_name='Name of the company')),
                ('description', models.TextField(verbose_name='Job description of the vacancy')),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapping.City')),
                ('Language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapping.Programming_Language')),
            ],
        ),
    ]
