# Generated by Django 3.0.14 on 2023-01-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_job_offers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City collection'},
        ),
        migrations.AlterModelOptions(
            name='job_offers',
            options={'verbose_name': 'Job offers collection model'},
        ),
        migrations.AlterModelOptions(
            name='programming_language',
            options={'verbose_name': 'Programming language collection'},
        ),
        migrations.RenameField(
            model_name='job_offers',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='job_offers',
            old_name='Language',
            new_name='language',
        ),
        migrations.AddField(
            model_name='job_offers',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_offers',
            name='urls',
            field=models.URLField(unique=True),
        ),
    ]
